// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBrLBnpYK2S15HMzd1-iXxS4MmOp5Hyz4',
    appId: '1:88314292158:web:9345879a2ca0d269c77bef',
    messagingSenderId: '88314292158',
    projectId: 'babyshop-4ce5e',
    authDomain: 'babyshop-4ce5e.firebaseapp.com',
    storageBucket: 'babyshop-4ce5e.appspot.com',
    measurementId: 'G-4JSH3MDYWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6N8tVVzPXQKH5wABL9w4YNR1TkRLZlVI',
    appId: '1:88314292158:android:69863a66fa9ca44fc77bef',
    messagingSenderId: '88314292158',
    projectId: 'babyshop-4ce5e',
    storageBucket: 'babyshop-4ce5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNvFXkeMKNU-ede0D63aICpmTZKAJv0I',
    appId: '1:88314292158:ios:9e547c6d6548716dc77bef',
    messagingSenderId: '88314292158',
    projectId: 'babyshop-4ce5e',
    storageBucket: 'babyshop-4ce5e.appspot.com',
    iosClientId: '88314292158-akgvb3l624rhsqmhn49pe0j9oann66tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNvFXkeMKNU-ede0D63aICpmTZKAJv0I',
    appId: '1:88314292158:ios:9e547c6d6548716dc77bef',
    messagingSenderId: '88314292158',
    projectId: 'babyshop-4ce5e',
    storageBucket: 'babyshop-4ce5e.appspot.com',
    iosClientId: '88314292158-akgvb3l624rhsqmhn49pe0j9oann66tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBrLBnpYK2S15HMzd1-iXxS4MmOp5Hyz4',
    appId: '1:88314292158:web:e3fe7293cc262b7ac77bef',
    messagingSenderId: '88314292158',
    projectId: 'babyshop-4ce5e',
    authDomain: 'babyshop-4ce5e.firebaseapp.com',
    storageBucket: 'babyshop-4ce5e.appspot.com',
    measurementId: 'G-2W4HJ57GNX',
  );

}